### ISSUE TITLE
Recuperação da Senha

### ISSUE THREAD

**Issue by rex5212** [rex5212/Fase_2_Iesb#4]

**Comment by rex5212** [comment]
![Recuperação da Senha - parte 1](https://user-images.githubusercontent.com/101425278/166177769-54e6aedf-beba-45c1-bcf2-3e29c9565f54.png)
![Recuperação da Senha - parte 2 v1](https://user-images.githubusercontent.com/101425278/166177771-db76d4be-34f6-49f7-95c4-93b1611c0ce1.png)
![Recuperação da Senha - parte 2 v2](https://user-images.githubusercontent.com/101425278/166177772-fe3e0b9e-421d-4a78-8153-167203c1fec0.png)
![Recuperação da Senha - parte 3](https://user-images.githubusercontent.com/101425278/166177774-911c84da-b531-4350-a238-f41eaccdbfa9.png)

**Comment by rex5212** [comment]
https://www.figma.com/file/jHvptBDOO2e6kcMgOEB7og/Trabalho-de-PI?node-id=10%3A2

**Comment by felipedevprofessional** [comment]
https://snack.expo.dev/@felipe.jesus/recuperarsenha
