### ISSUE TITLE
Inicial

### ISSUE THREAD

**Issue by rex5212** [rex5212/Fase_2_Iesb#7]

**Comment by rex5212** [comment]
![Inicial - Continua 3](https://user-images.githubusercontent.com/101425278/166177838-3094fd81-8b7a-42ec-bc83-e515a0d638f3.png)
![Inicial - Continuação 2](https://user-images.githubusercontent.com/101425278/166177841-01736580-0aa4-4413-9367-58ed157f6677.png)
![Inicial](https://user-images.githubusercontent.com/101425278/166177842-b2a1657d-e02c-40b3-8a4f-35bc84dac675.png)

**Comment by rex5212** [comment]
https://www.figma.com/file/jHvptBDOO2e6kcMgOEB7og/Trabalho-de-PI?node-id=10%3A2

**Comment by rex5212** [comment]
veja o figma,
 grande mudança no projeto

**Comment by rex5212** [comment]
![Inicial - Continua 5](https://user-images.githubusercontent.com/101425278/168484261-39499720-9b45-411e-98f5-1a39c323cf04.png)

**Comment by felipedevprofessional** [comment]
https://snack.expo.dev/@felipe.jesus/inicial

Até o momento ta assim a parte do inicial
