### ISSUE TITLE
Menu

### ISSUE THREAD

**Issue by rex5212** [rex5212/Fase_2_Iesb#9]

**Comment by rex5212** [comment]
![Menu](https://user-images.githubusercontent.com/101425278/166177879-3ba398c0-2f2a-496b-8b24-32295dca4785.png)
![Troca Email](https://user-images.githubusercontent.com/101425278/166177880-1ca5ede2-c472-4a8e-a038-3e7fc8fdd5a8.png)
![Troca Nome](https://user-images.githubusercontent.com/101425278/166177882-33467490-63e8-4414-b9a3-9cd7516fa137.png)
![Troca Senha](https://user-images.githubusercontent.com/101425278/166177884-25f528e7-62d1-48c4-a039-aba9d25e5466.png)

**Comment by rex5212** [comment]
https://www.figma.com/file/jHvptBDOO2e6kcMgOEB7og/Trabalho-de-PI?node-id=10%3A2

**Comment by felipedevprofessional** [comment]
https://snack.expo.dev/@felipe.jesus/trocarsenhamenu
